"""
generate_submission.py — Generates submission.jsonl (30 test pairs).

Usage:
    python generate_submission.py

The script:
1. Loads the dataset (expanded or seed)
2. Loads test_pairs.json (generated by dataset/generate_dataset.py)
   OR uses the hardcoded 25 seed trigger pairs as fallback
3. Runs compose() on each pair
4. Writes submission.jsonl (30 lines)

Set your LLM provider before running:
    set LLM_PROVIDER=gemini
    set LLM_API_KEY=your_key_here
    python generate_submission.py
"""

import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from bot import compose
from compose_engine import llm_client

# ─────────────────────────────────────────────────────────────────────────────
# DATASET LOADING
# ─────────────────────────────────────────────────────────────────────────────

def load_dataset(dataset_dir: Path) -> tuple[dict, dict, dict, dict]:
    """Returns (categories, merchants, customers, triggers) as dicts keyed by ID."""
    categories = {}
    merchants = {}
    customers = {}
    triggers = {}

    expanded = dataset_dir / "expanded"

    if expanded.exists():
        print(f"[LOAD] Using expanded dataset from {expanded}", flush=True)
        for f in (expanded / "categories").glob("*.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            categories[data["slug"]] = data
        for f in (expanded / "merchants").glob("*.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            merchants[data["merchant_id"]] = data
        for f in (expanded / "customers").glob("*.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            customers[data["customer_id"]] = data
        for f in (expanded / "triggers").glob("*.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            triggers[data["id"]] = data
    else:
        print(f"[LOAD] Using seed dataset (run dataset/generate_dataset.py for full set)", flush=True)
        for f in (dataset_dir / "categories").glob("*.json"):
            data = json.loads(f.read_text(encoding="utf-8"))
            categories[data["slug"]] = data
        for m in json.loads((dataset_dir / "merchants_seed.json").read_text(encoding="utf-8"))["merchants"]:
            merchants[m["merchant_id"]] = m
        for c in json.loads((dataset_dir / "customers_seed.json").read_text(encoding="utf-8"))["customers"]:
            customers[c["customer_id"]] = c
        for t in json.loads((dataset_dir / "triggers_seed.json").read_text(encoding="utf-8"))["triggers"]:
            triggers[t["id"]] = t

    print(f"[LOAD] categories={len(categories)} merchants={len(merchants)} customers={len(customers)} triggers={len(triggers)}", flush=True)
    return categories, merchants, customers, triggers


def load_test_pairs(dataset_dir: Path, triggers: dict) -> list[dict]:
    """Load test_pairs.json if it exists, else build from all seed triggers."""
    expanded_pairs = dataset_dir / "expanded" / "test_pairs.json"
    if expanded_pairs.exists():
        data = json.loads(expanded_pairs.read_text(encoding="utf-8"))
        pairs = data.get("pairs", [])
        print(f"[PAIRS] Loaded {len(pairs)} pairs from test_pairs.json", flush=True)
        return pairs[:30]

    # Fallback: use all available triggers, up to 30
    print("[PAIRS] No test_pairs.json found — using all available triggers (up to 30)", flush=True)
    pairs = []
    for i, (tid, t) in enumerate(list(triggers.items())[:30]):
        pairs.append({
            "test_id": f"T{i+1:02d}",
            "trigger_id": tid,
            "merchant_id": t.get("merchant_id", ""),
            "customer_id": t.get("customer_id"),
        })
    return pairs


# ─────────────────────────────────────────────────────────────────────────────
# MAIN GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_submission(output_path: Path, dry_run: bool = False):
    dataset_dir = Path(__file__).parent / "dataset"
    categories, merchants, customers, triggers = load_dataset(dataset_dir)
    pairs = load_test_pairs(dataset_dir, triggers)

    print(f"\n[GEN] Generating {len(pairs)} messages with {llm_client.provider_name()}", flush=True)
    print(f"[GEN] Output: {output_path}", flush=True)
    print("=" * 60, flush=True)

    results = []
    errors = []

    for pair in pairs:
        test_id = pair["test_id"]
        trigger_id = pair["trigger_id"]
        merchant_id = pair["merchant_id"]
        customer_id = pair.get("customer_id")

        trigger = triggers.get(trigger_id)
        merchant = merchants.get(merchant_id)

        if not trigger:
            print(f"  [{test_id}] SKIP — trigger not found: {trigger_id}", flush=True)
            continue
        if not merchant:
            print(f"  [{test_id}] SKIP — merchant not found: {merchant_id}", flush=True)
            continue

        cat_slug = merchant.get("category_slug", "")
        category = categories.get(cat_slug)
        if not category:
            print(f"  [{test_id}] SKIP — category not found: {cat_slug}", flush=True)
            continue

        customer = customers.get(customer_id) if customer_id else None

        if dry_run:
            print(f"  [{test_id}] DRY-RUN — {merchant.get('identity',{}).get('name','?')} + {trigger.get('kind','?')}", flush=True)
            continue

        start = time.time()
        try:
            result = compose(category, merchant, trigger, customer)
            elapsed = (time.time() - start) * 1000

            line = {
                "test_id": test_id,
                "trigger_id": trigger_id,
                "merchant_id": merchant_id,
                "customer_id": customer_id,
                "body": result["body"],
                "cta": result["cta"],
                "send_as": result["send_as"],
                "suppression_key": result["suppression_key"],
                "rationale": result["rationale"],
            }
            results.append(line)

            preview = result["body"][:70].replace("\n", " ")
            print(f"  [{test_id}] ✓ {elapsed:.0f}ms | {result['send_as']} | cta={result['cta']}", flush=True)
            print(f"          \"{preview}...\"", flush=True)

        except Exception as e:
            elapsed = (time.time() - start) * 1000
            print(f"  [{test_id}] ✗ ERROR ({elapsed:.0f}ms): {e}", flush=True)
            errors.append({"test_id": test_id, "error": str(e)})
            # Write a placeholder so we still have 30 lines
            results.append({
                "test_id": test_id,
                "trigger_id": trigger_id,
                "merchant_id": merchant_id,
                "customer_id": customer_id,
                "body": f"[Generation failed: {str(e)[:80]}]",
                "cta": "none",
                "send_as": "vera",
                "suppression_key": trigger_id,
                "rationale": "LLM generation failed",
            })

    if dry_run:
        print(f"\n[DRY-RUN] Would generate {len(pairs)} messages. No output written.", flush=True)
        return

    # Write JSONL
    with open(output_path, "w", encoding="utf-8") as f:
        for line in results:
            f.write(json.dumps(line, ensure_ascii=False) + "\n")

    print("=" * 60, flush=True)
    print(f"\n[DONE] Written {len(results)} lines to {output_path}", flush=True)
    if errors:
        print(f"[WARN] {len(errors)} error(s) encountered:", flush=True)
        for e in errors:
            print(f"  {e['test_id']}: {e['error']}", flush=True)
    else:
        print("[DONE] All messages generated successfully! ✓", flush=True)

    # Print score preview
    print(f"\n[PREVIEW] First 3 messages:", flush=True)
    for r in results[:3]:
        print(f"\n  {r['test_id']} ({r['send_as']}, cta={r['cta']}):", flush=True)
        print(f"  {r['body'][:200]}", flush=True)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate submission.jsonl for magicpin AI Challenge")
    parser.add_argument("--output", default="submission.jsonl", help="Output JSONL path")
    parser.add_argument("--dry-run", action="store_true", help="Preview pairs without calling LLM")
    args = parser.parse_args()

    output = Path(args.output)
    generate_submission(output, dry_run=args.dry_run)
